/**
 * 店内常用商品资料 + 产品目录全线。
 * 参考售价来自京东/华强北行情；目录条目可只入库不经营。
 */
import { CPU_CATALOG } from "@/lib/product-catalog-cpu";
import { GPU_CATALOG } from "@/lib/product-catalog-gpu";
import { MB_CATALOG } from "@/lib/product-catalog-mb";
import { RAM_CATALOG } from "@/lib/product-catalog-ram";
import { STORAGE_CATALOG } from "@/lib/product-catalog-storage";
import { PSU_MISC_CATALOG } from "@/lib/product-catalog-psu";
import { LENOVO_CATALOG } from "@/lib/product-catalog-lenovo";
import { NET_CATALOG } from "@/lib/product-catalog-net";
import { CCTV_CATALOG } from "@/lib/product-catalog-cctv";
import { PRT_CONS_CATALOG } from "@/lib/product-catalog-prt";
import { KIT_CATALOG } from "@/lib/product-catalog-kits";
import { SELFLOAD_CATALOG } from "@/lib/product-catalog-selfload";
import type { CatalogProduct } from "@/lib/product-catalog-item";

export type { CatalogProduct };

export const PRODUCT_CATALOG: CatalogProduct[] = [
  ...CPU_CATALOG,
  ...MB_CATALOG,
  ...GPU_CATALOG,
  ...RAM_CATALOG,
  ...STORAGE_CATALOG,
  ...PSU_MISC_CATALOG,
  ...LENOVO_CATALOG,
  ...NET_CATALOG,
  ...CCTV_CATALOG,
  ...PRT_CONS_CATALOG,
  ...KIT_CATALOG,
  ...SELFLOAD_CATALOG,
  // —— 内存 ——
  {
    code: "RAM16",
    name: "FURY 野兽 DDR4 16G 3200",
    brand: "金士顿",
    spec: "HX432C16FB3/16 单条",
    unit: "条",
    cat: "PC-RAM",
    sale: 219,
    cost: 155,
    stock: 12,
    warranty: 36,
    remark: "京东骇客神条 DDR4 16G 约 189–249。办公双通道买两条。",
    images: [
      "https://media.kingston.com/kingston/product/ktc-product-memory-beast-ddr4-1-zm-lg.jpg",
      "https://media.kingston.com/kingston/hero/ktc-hero-memory-beast-ddr4-lg.jpg",
    ],
  },
  {
    code: "RAM32",
    name: "FURY 野兽 DDR5 32G 6000",
    brand: "金士顿",
    spec: "16G×2 套装 CL36 EXPO/XMP",
    unit: "套",
    cat: "PC-RAM",
    sale: 599,
    cost: 430,
    stock: 8,
    warranty: 36,
    remark: "京东 32G(16×2) 6000 套装常见约 499–699。",
    images: [
      "https://media.kingston.com/kingston/product/ktc-product-memory-beast-ddr5-kit-1-zm-lg.jpg",
      "https://media.kingston.com/kingston/product/ktc-product-fury-beast-ddr5-1-zm-lg.jpg",
    ],
  },
  {
    code: "RAM64",
    name: "FURY 野兽 DDR5 64G 6000",
    brand: "金士顿",
    spec: "32G×2 套装 CL36",
    unit: "套",
    cat: "PC-RAM",
    sale: 1199,
    cost: 890,
    stock: 4,
    warranty: 36,
    remark: "京东 64G 套装约 1099–1399。设计/高端机用。",
    images: [
      "https://media.kingston.com/kingston/product/ktc-product-memory-beast-ddr5-1-zm-lg.jpg",
    ],
  },
  // —— 硬盘 / 固态 ——
  {
    code: "SSD512",
    name: "SN5000 蓝盘 500G NVMe",
    brand: "西数",
    spec: "PCIe 4.0 M.2 2280",
    unit: "块",
    cat: "PC-SSD",
    sale: 259,
    cost: 185,
    stock: 10,
    remark: "京东西数蓝盘 500G 约 229–279。",
    images: [
      "https://www.westerndigital.com/content/dam/store/en-us/assets/products/internal-storage/wd-blue-sn5000-nvme-ssd/gallery/wd-blue-sn5000-nvme-ssd-front.png",
      "https://documents.westerndigital.com/content/dam/doc-library/en_us/assets/public/western-digital/product/internal-drives/wd-blue-ssd/photo/wd-blue-sn580-nvme-ssd-front.png",
    ],
  },
  {
    code: "SSD1T",
    name: "990 EVO Plus 1TB",
    brand: "三星",
    spec: "MZ-V9S1T0BW PCIe4.0 读 7150MB/s",
    unit: "块",
    cat: "PC-SSD",
    sale: 549,
    cost: 410,
    stock: 8,
    remark: "京东自营 990 EVO Plus 1T 约 500–599。",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/uk/mz-v9s1t0bw/gallery/uk-990-evo-plus-nvme-m2-ssd-mz-v9s1t0bw-539575-mz-v9s1t0bw-530973238?$650_519_PNG$",
      "https://images.samsung.com/is/image/samsung/p6pim/uk/mz-v9s1t0bw/gallery/uk-990-evo-plus-nvme-m2-ssd-mz-v9s1t0bw-mz-v9s1t0bw-530973254?$684_547_PNG$",
    ],
  },
  {
    code: "SSD2T",
    name: "990 EVO Plus 2TB",
    brand: "三星",
    spec: "MZ-V9S2T0BW PCIe4.0",
    unit: "块",
    cat: "PC-SSD",
    sale: 899,
    cost: 680,
    stock: 4,
    remark: "京东 2T 约 799–999。",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/uk/mz-v9s2t0bw/gallery/uk-990-evo-plus-nvme-m2-ssd-mz-v9s2t0bw-539576-mz-v9s2t0bw-530973272?$650_519_PNG$",
    ],
  },
  {
    code: "HDD1T",
    name: "希捷酷鱼 1TB 7200转",
    brand: "希捷",
    spec: "ST1000DM014 3.5 英寸 SATA",
    unit: "块",
    cat: "PC-HDD",
    sale: 329,
    cost: 245,
    stock: 3,
    warranty: 24,
    trackSerial: true,
    remark: "京东酷鱼 1T 约 299–349。管唯一 SN。",
    images: [
      "https://www.seagate.com/content/dam/seagate/migrated-assets/www-content/product-content/internal-hdd-fam/barracuda/en-us/images/product-landing-baracuda-main.png",
      "https://www.seagate.com/content/dam/seagate/migrated-assets/www-content/product-content/internal-hdd-fam/barracuda/en-us/gallery/baracuda-3-5-hero.png",
    ],
  },
  // —— 电源 / 机箱 / 散热 ——
  {
    code: "PSU-550",
    name: "WD550K 额定 550W 铜牌",
    brand: "航嘉",
    spec: "直出线 80PLUS 铜牌",
    unit: "个",
    cat: "PC-PSU",
    sale: 249,
    cost: 180,
    stock: 6,
    remark: "京东航嘉 550W 约 219–279。办公机。",
    images: [
      "https://www.huntkey.com/upload/product/wd550k.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/17-139-019-V01.jpg",
    ],
  },
  {
    code: "PSU-750",
    name: "FOCUS GX-750 金牌全模",
    brand: "海韵",
    spec: "额定 750W ATX 金牌",
    unit: "个",
    cat: "PC-PSU",
    sale: 699,
    cost: 530,
    stock: 4,
    remark: "京东海韵 FOCUS GX-750 约 649–749。",
    images: [
      "https://seasonic.com/wp-content/uploads/focus-gx-750.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/17-110-152-V01.jpg",
    ],
  },
  {
    code: "PSU-850",
    name: "FOCUS GX-850 金牌全模",
    brand: "海韵",
    spec: "额定 850W ATX 金牌",
    unit: "个",
    cat: "PC-PSU",
    sale: 799,
    cost: 610,
    stock: 3,
    remark: "京东 GX-850 约 749–899。",
    images: [
      "https://seasonic.com/wp-content/uploads/focus-gx-850.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/17-110-153-V01.jpg",
    ],
  },
  {
    code: "PSU-1200",
    name: "TG-1200 金牌全模",
    brand: "利民",
    spec: "额定 1200W ATX3.0",
    unit: "个",
    cat: "PC-PSU",
    sale: 1099,
    cost: 820,
    stock: 2,
    remark: "京东利民/长城 1200W 档约 999–1199。4090 用。",
    images: [
      "https://www.thermalright.com/wp-content/uploads/tg1200.png",
    ],
  },
  {
    code: "CASE-OFFICE",
    name: "小咖 办公 MATX 机箱",
    brand: "先马",
    spec: "MATX 前置 USB 预装风扇",
    unit: "个",
    cat: "PC-CASE",
    sale: 149,
    cost: 95,
    stock: 6,
    remark: "京东先马办公小机箱约 129–179。",
    images: [
      "https://www.sama.com.cn/upload/case-office.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/11-148-079-V01.jpg",
    ],
  },
  {
    code: "CASE-GAME",
    name: "LANCOOL 216 海景房",
    brand: "联力",
    spec: "中塔 ATX 高风量",
    unit: "个",
    cat: "PC-CASE",
    sale: 399,
    cost: 290,
    stock: 4,
    remark: "京东联力 216 约 349–449。",
    images: [
      "https://www.lian-li.com/wp-content/uploads/2022/11/lancool-216-black.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/11-139-176-V01.jpg",
    ],
  },
  {
    code: "CASE-WS",
    name: "P400A 创作用中塔",
    brand: "追风者",
    spec: "ATX 网孔前面板",
    unit: "个",
    cat: "PC-CASE",
    sale: 449,
    cost: 320,
    stock: 3,
    remark: "京东追风者 P400A 约 399–499。",
    images: [
      "https://www.phanteks.com/images/product/P400A/P400A-BK.png",
    ],
  },
  {
    code: "CASE-HIGH",
    name: "O11D EVO 全塔海景",
    brand: "联力",
    spec: "ATX 双面玻璃 水冷位充足",
    unit: "个",
    cat: "PC-CASE",
    sale: 799,
    cost: 560,
    stock: 2,
    remark: "京东 O11D EVO 约 699–899。",
    images: [
      "https://www.lian-li.com/wp-content/uploads/2022/01/o11d-evo-black.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/11-139-169-V01.jpg",
    ],
  },
  {
    code: "COOL-STOCK",
    name: "原装下压风冷",
    brand: "英特尔",
    spec: "盒装 CPU 附送散热器",
    unit: "个",
    cat: "PC-COOL",
    sale: 49,
    cost: 20,
    stock: 10,
    remark: "i3/部分 i5 盒装自带，单卖给办公机。",
    images: [
      "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-08/laminar-rm1-cooler.png",
    ],
  },
  {
    code: "COOL-TOWER",
    name: "PA120 双塔风冷",
    brand: "利民",
    spec: "Peerless Assassin 120",
    unit: "个",
    cat: "PC-COOL",
    sale: 129,
    cost: 85,
    stock: 6,
    remark: "京东利民 PA120 约 99–149。性价比神器。",
    images: [
      "https://www.thermalright.com/wp-content/uploads/peerless-assassin-120.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/35-181-061-V01.jpg",
    ],
  },
  {
    code: "COOL-AIO240",
    name: "冰魔方 240 一体水冷",
    brand: "恩杰",
    spec: "240mm 冷排 RGB 水泵",
    unit: "套",
    cat: "PC-COOL",
    sale: 399,
    cost: 290,
    stock: 3,
    remark: "京东 240 水冷入门约 349–499。",
    images: [
      "https://nzxt.com/assets/cms/kraken-240.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/35-145-191-V01.jpg",
    ],
  },
  {
    code: "COOL-AIO360",
    name: "冰魔方 360 一体水冷",
    brand: "恩杰",
    spec: "360mm 冷排 高端机",
    unit: "套",
    cat: "PC-COOL",
    sale: 699,
    cost: 510,
    stock: 2,
    remark: "京东 360 水冷约 599–799。i9/4090 用。",
    images: [
      "https://nzxt.com/assets/cms/kraken-360.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/35-145-192-V01.jpg",
    ],
  },
  {
    code: "FAN-C12C",
    name: "TL-C12C 12cm 机箱风扇",
    brand: "利民",
    spec: "120mm 液压轴承 3pin",
    unit: "个",
    cat: "PC-FAN",
    sale: 19,
    cost: 9,
    stock: 20,
    remark: "京东利民 C12C 约 15–25。",
    images: ["https://www.thermalright.com/wp-content/uploads/tl-c12c.png"],
  },
  // —— 显示器 / 键鼠 ——
  {
    code: "MON-AOC24",
    name: "24B35H 23.8 英寸显示器",
    brand: "AOC",
    spec: "1080P 100Hz VGA+HDMI",
    unit: "台",
    cat: "PC-MON",
    sale: 499,
    cost: 380,
    stock: 5,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东 AOC 24 寸办公屏约 459–549。",
    images: [
      "https://www.aoc.com/image/24B35H.png",
      "https://c1.neweggimages.com/ProductImageCompressAll1280/24-004-xxx.jpg",
    ],
  },
  {
    code: "MON-MI27",
    name: "G Pro 27i 2K 180Hz",
    brand: "小米",
    spec: "27 英寸 Fast IPS 升降旋转",
    unit: "台",
    cat: "PC-MON",
    sale: 1299,
    cost: 1050,
    stock: 3,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东小米 G Pro 27i 约 1199–1399。",
    images: [
      "https://cdn.cnbj1.fds.api.mi-img.com/product-images/xiaomi-display-g-pro-27i.png",
    ],
  },
  {
    code: "KM-MK270",
    name: "MK270 无线键鼠套装",
    brand: "罗技",
    spec: "2.4G 优联 全尺寸键盘",
    unit: "套",
    cat: "PC-KM",
    sale: 129,
    cost: 85,
    stock: 10,
    canBeBuildPart: false,
    remark: "京东罗技 MK270 约 99–139。",
    images: [
      "https://resource.logitech.com/content/dam/logitech/en/products/combos/mk270-wireless/gallery/mk270-gallery-1.png",
      "https://resource.logitechg.com/w_692,c_limit,q_auto,f_auto,dpr_auto/d_transparent.gif/content/dam/logitech/en/products/combos/mk270/gallery/mk270-gallery-1.png",
    ],
  },
  {
    code: "KM-G102",
    name: "G102 第二代游戏鼠标",
    brand: "罗技",
    spec: "8000DPI RGB 有线",
    unit: "个",
    cat: "PC-KM",
    sale: 89,
    cost: 58,
    stock: 12,
    canBeBuildPart: false,
    remark: "京东 G102 约 69–99。",
    images: [
      "https://resource.logitechg.com/w_692,c_limit,q_auto,f_auto,dpr_auto/d_transparent.gif/content/dam/gaming/en/products/g102-lightsync/g102-lightsync-gallery-1.png",
    ],
  },
  {
    code: "AUDIO-K800",
    name: "K800 头戴式耳机",
    brand: "漫步者",
    spec: "3.5mm 单孔 办公网课",
    unit: "个",
    cat: "PC-AUDIO",
    sale: 69,
    cost: 42,
    stock: 8,
    canBeBuildPart: false,
    remark: "京东漫步者入门耳机约 59–79。",
    images: ["https://www.edifier.com/upload/k800.png"],
  },
  {
    code: "MISC-HDMI",
    name: "HDMI 2.0 高清线 1.5 米",
    brand: "绿联",
    spec: "4K60 镀金接头",
    unit: "根",
    cat: "PC-MISC",
    sale: 29,
    cost: 12,
    stock: 20,
    canBeBuildPart: true,
    remark: "京东绿联 1.5 米约 19–39。",
    images: ["https://www.ugreen.com/cdn/shop/products/hdmi-cable.png"],
  },
  {
    code: "MISC-PASTE",
    name: "MX-4 导热硅脂 4g",
    brand: "爱民",
    spec: "装机辅材",
    unit: "支",
    cat: "PC-MISC",
    sale: 35,
    cost: 18,
    stock: 15,
    canBeBuildPart: true,
    remark: "京东 Arctic MX-4 约 29–45。",
    images: ["https://www.arctic.de/media/mx4.png"],
  },
  // —— 笔记本 / 品牌机 ——
  {
    code: "NB-R7000",
    name: "拯救者 R7000 2024",
    brand: "联想",
    spec: "R7-8745H RTX 4060 16G 512G 15.6",
    unit: "台",
    cat: "NB-GAME",
    sale: 6499,
    cost: 5980,
    stock: 2,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东拯救者 R7000 4060 款约 6299–6799。",
    images: [
      "https://p1.lefile.cn/product/lenovo-legion-r7000.png",
      "https://p3.lefile.cn/fes/cms/2024/legion-r7000-front.png",
    ],
  },
  {
    code: "NB-XIAOXIN",
    name: "小新 14 2024 酷睿版",
    brand: "联想",
    spec: "i5-13420H 16G 512G 14 英寸",
    unit: "台",
    cat: "NB-UNIT",
    sale: 4299,
    cost: 3890,
    stock: 3,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东小新 14 办公本约 3999–4499。",
    images: ["https://p1.lefile.cn/product/xiaoxin-14-2024.png"],
  },
  {
    code: "BRAND-QITIAN",
    name: "启天 M460 商用主机",
    brand: "联想",
    spec: "i5-13400 16G 512G 无显示器",
    unit: "台",
    cat: "BRAND-DT",
    sale: 3999,
    cost: 3520,
    stock: 2,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东联想启天/扬天商用约 3799–4299。",
    images: ["https://p1.lefile.cn/product/qitian-m460.png"],
  },
  // —— 网络 ——
  {
    code: "NET-XDR3010",
    name: "XDR3010 飞流 WiFi6",
    brand: "TP-LINK",
    spec: "AX3000 双频 千兆网口",
    unit: "台",
    cat: "NET-RT",
    sale: 219,
    cost: 155,
    stock: 6,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东 TP-LINK AX3000 约 189–249。",
    images: [
      "https://static.tp-link.com/upload/image-product/XDR3010/XDR3010_un_1.0_01_normal_20220112102526n.png",
      "https://static.tp-link.com.cn/web/upload/image/product/XDR3010.png",
    ],
  },
  {
    code: "NET-SG1008",
    name: "TL-SG1008D 8 口千兆",
    brand: "TP-LINK",
    spec: "非网管 桌面式",
    unit: "台",
    cat: "NET-SW",
    sale: 89,
    cost: 58,
    stock: 6,
    canBeBuildPart: false,
    remark: "京东 8 口千兆交换机约 75–99。",
    images: [
      "https://static.tp-link.com/res/images/products/TL-SG1008D_un_V9_01_normal_20201120154131j.png",
    ],
  },
  {
    code: "NET-CAT6",
    name: "超六类网线 305 米箱",
    brand: "秋叶原",
    spec: "CAT6 工程箱线",
    unit: "箱",
    cat: "NET-CABLE",
    sale: 320,
    cost: 210,
    stock: 4,
    canBeBuildPart: false,
    remark: "京东/淘宝工程网线箱约 280–360。",
    images: ["https://www.choseal.com/upload/cat6-box.png"],
  },
  // —— 监控 ——
  {
    code: "CCTV-T12H",
    name: "DS-IPC-T12HV3-IA 200 万",
    brand: "海康威视",
    spec: "POE 红外半球 拾音",
    unit: "台",
    cat: "CCTV-IP",
    sale: 189,
    cost: 135,
    stock: 8,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东海康 200 万半球约 169–219。",
    images: [
      "https://www.hikvision.com/content/dam/hikvision/products/ipc/t12hv3.png",
      "https://www.hikvision.com.cn/upload8/image/t12h.png",
    ],
  },
  {
    code: "CCTV-NVR4",
    name: "DS-7104N-F1 4 路 NVR",
    brand: "海康威视",
    spec: "4 路接入 带 POE",
    unit: "台",
    cat: "CCTV-NVR",
    sale: 329,
    cost: 245,
    stock: 3,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东 4 路 NVR 约 299–379。",
    images: ["https://www.hikvision.com/content/dam/hikvision/products/nvr/ds-7104n-f1.png"],
  },
  {
    code: "CCTV-WD4T",
    name: "紫盘 4TB 监控级",
    brand: "西数",
    spec: "WD40PURZ 3.5 英寸",
    unit: "块",
    cat: "CCTV-HDD",
    sale: 599,
    cost: 460,
    stock: 3,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东西数紫盘 4T 约 549–649。",
    images: [
      "https://www.westerndigital.com/content/dam/store/en-us/assets/products/internal-storage/wd-purple-hdd/gallery/wd-purple-hdd-front.png",
    ],
  },
  // —— 打印 / 耗材 ——
  {
    code: "PRT-HP136W",
    name: "Laser 136w 无线激光一体机",
    brand: "惠普",
    spec: "打印复印扫描 WiFi",
    unit: "台",
    cat: "PRT-MFP",
    sale: 1099,
    cost: 890,
    stock: 2,
    trackSerial: true,
    canBeBuildPart: false,
    remark: "京东 HP 136w 约 999–1199。",
    images: [
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06608512.png",
      "https://www.hp.com/us-en/shop/app/us/web/content/images/product/laser-136w.png",
    ],
  },
  {
    code: "CONS-136A",
    name: "W1360A 136A 硒鼓",
    brand: "惠普",
    spec: "约 1150 页 原装黑",
    unit: "个",
    cat: "CONS-DRUM",
    sale: 329,
    cost: 250,
    stock: 6,
    canBeBuildPart: false,
    remark: "京东原装 136A 约 299–359。",
    images: [
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06644180.png",
    ],
  },
  {
    code: "CONS-A4",
    name: "A4 复印纸 70g 500 张",
    brand: "得力",
    spec: "单包",
    unit: "包",
    cat: "CONS-PAPER",
    sale: 22,
    cost: 14,
    stock: 30,
    canBeBuildPart: false,
    remark: "京东得力 A4 70g 约 18–25。",
    images: ["https://img.deli.com.cn/a4-paper.png"],
  },
  // —— 服务（无图也可）——
  {
    code: "VISIT",
    name: "上门费",
    brand: "",
    spec: "市区上门",
    unit: "次",
    cat: "SVC-VISIT",
    sale: 80,
    cost: 0,
    stock: 0,
    warranty: 0,
    isStocked: false,
    canBeBuildPart: false,
    images: [],
  },
  {
    code: "LABOR",
    name: "组装工时",
    brand: "",
    spec: "组装一台",
    unit: "次",
    cat: "SVC-BUILD",
    sale: 150,
    cost: 0,
    stock: 0,
    warranty: 0,
    isStocked: false,
    canBeBuildPart: false,
    images: [],
  },
  {
    code: "SVC-REPAIR",
    name: "维修工时",
    brand: "",
    spec: "到店检测维修（不含配件）",
    unit: "次",
    cat: "SVC-REPAIR",
    sale: 80,
    cost: 0,
    stock: 0,
    warranty: 0,
    isStocked: false,
    canBeBuildPart: false,
    images: [],
  },
  {
    code: "SVC-TEST",
    name: "检测费",
    brand: "",
    spec: "主机/笔记本检测出报告",
    unit: "次",
    cat: "SVC-TEST",
    sale: 50,
    cost: 0,
    stock: 0,
    warranty: 0,
    isStocked: false,
    canBeBuildPart: false,
    images: [],
  },
  {
    code: "SVC-OUTSRC",
    name: "委外维修",
    brand: "",
    spec: "客户配件送外厂维修（不扣本店库存）",
    unit: "次",
    cat: "SVC-OUTSRC",
    sale: 0,
    cost: 0,
    stock: 0,
    warranty: 0,
    isStocked: false,
    canBeBuildPart: false,
    images: [],
  },
];
